cs122/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from django.shortcuts import render


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('meethalfway.urls', namespace="meethalfway")),
]

meethalfway/urls.py
from django.conf.urls import url, patterns, include
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'home', views.home, name='home'),
    url(r'^new_meeting/(?P<trip_id>[a-z]+-[a-z]+-[a-z]+)', views.new_meeting, name = 'new_meeting'),
    url(r'^participant_two/(?P<trip_id>[a-z]+-[a-z]+-[a-z]+)', views.participant_two, name = 'participant_two'),
    url(r'^results/(?P<trip_id>[a-z]+-[a-z]+-[a-z]+)', views.results, name = 'results'),
    url(r'^address_error1/(?P<suggestion>.*)', views.address_error1, name = 'address_error1'),
    url(r'^address_error2/(?P<trip_id>[a-z]+-[a-z]+-[a-z]+)(?P<suggestion>.*)', views.address_error2, name = 'address_error2'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^no_results', views.no_results, name='no_results'),
    url(r'$', views.home, name='home')

]
# urlpatterns += staticfiles_urlpatterns()

meethalfway/views.py
from django.shortcuts import render, redirect
import csv
import time
import json
import requests
from django.core.urlresolvers import reverse
from django import forms
from . import models


class EnterIDForm(forms.Form):
    '''
    Short form to enter in a meeting ID. Validate_trip_id function cleans the
    ID and checks if it is in the database; if it isn't, returns None.
    '''
    trip_id = forms.CharField()
    def validate_trip_id(self):
        cleaned_id = self.cleaned_data
        if models.Meeting.objects.filter(trip_id = cleaned_id['trip_id']):
            return cleaned_id['trip_id']
        else:
            return None


class AddAddress(forms.ModelForm):
    '''
    ModelForm connected to the Address model. Provides field for street, city,
    state, and zip code.
    '''
    class Meta:
        model = models.Address
        fields = ["street", "city", "state", "zip_code"]


class AddParticipant(forms.ModelForm):
    '''
    ModelForm connected to the Paricipant model. Provides a menu of valid modes
    of transport. An address is combined with mode of transit to create a Participant
    '''
    class Meta:
        model = models.Participant
        fields = ["transit_mode"]
        widgets = {
            'transit_mode': forms.Select(),
        }


class AddMeeting(forms.ModelForm):
    '''
    ModelForm connected to the Meeting model. Provides a menu of valid business
    types. Created when a participant is added and initialized with empty values for
    participant_two and destinations.
    '''
    class Meta:
        model = models.Meeting
        fields = ["business_type"]
        widgets = {
            'business_type': forms.Select()
        }


def home(request):
    '''
    View for home page of MeetHalfway. Contains forms for the first participant to
    enter their address, mode of transit, and business type for meeting. Validates
    the address provided using a service from USPS. With completed form, creates an
    Address, Participant, and Meeting then generates a unique Meeting ID. Also
    displays a form to enter in the ID of a previously created meeting. If valid,
    either redirects to a page for the second participant to enter information or
    displays results if second person's information has already been added. If
    invalid, displays error message.
    '''
    error = None
    if request.method == 'POST':
        if "participant_one_submit" in request.POST:
            address = AddAddress(request.POST)
            participant = AddParticipant(request.POST)
            meeting = AddMeeting(request.POST)
            #USPS api used to validate the entered address
            if address.is_valid() and participant.is_valid() and meeting.is_valid():
                trip_id, suggestion = participant_one(request, address, participant, meeting)
                if trip_id != None:
                    return redirect('meethalfway:new_meeting', trip_id)
                else:
                    #Returns error message if address invalid
                    return redirect('meethalfway:address_error1',suggestion)
        elif 'enter_trip_id' in request.POST:
            trip_id = EnterIDForm(request.POST)
            if trip_id.is_valid():
                valid_trip_id = trip_id.validate_trip_id()
                if valid_trip_id:
                    meeting = models.Meeting.objects.get(trip_id = valid_trip_id)
                    if not meeting.participant_two:
                        #Redirects to form for participant two if not filled in
                        return redirect('meethalfway:participant_two', valid_trip_id)
                    else:
                        #Redirects to results if information already filled int
                        return redirect('meethalfway:results', valid_trip_id)
                else:
                    #Error if invalid trip id is entered
                    error = True
    address = AddAddress()
    participant = AddParticipant()
    meeting = AddMeeting()
    trip_id = EnterIDForm()

    c = {
        'forms': [address, participant, meeting],
        'trip_id_form': trip_id,
        'not_found' : error
    }
    return render(request, 'halfwayapp/home.html', c)


def new_meeting(request, trip_id):
    '''
    Displays the trip id generated after participant one enters information.
    '''
    return render(request,'halfwayapp/response.html', {'uniq' : trip_id})


def participant_one(request, address, participant, meeting):
    '''
    Function to verify the address of the first participant and to create and save
    the Address, Participant, and Meeting objects for the new meeting.
    '''
    address_obj = address.save()
    verify, suggestion,verified_address_dict = address_obj.verify_address()
    if verify:
        verified_address = models.Address(street = verified_address_dict['address'], city = verified_address_dict['city'], \
        state = verified_address_dict['state'], zip_code = verified_address_dict['zip5'])
        verified_address.save()
        address_obj.delete()

        part_obj = participant.save()
        part_obj.starting_location = verified_address
        part_obj.save()

        meeting_obj = meeting.save()
        meeting_obj.participant_one = part_obj
        meeting_obj.trip_id = meeting_obj.random_words()
        meeting_obj.save()
    else:
        #Returns error message if address invalid
        return None, suggestion

    return meeting_obj.trip_id, None


def participant_two(request, trip_id):
    '''
    Handles information passed to create the second participant in a Meeting. If
    a second participant has already been added, redirects to results. Otherwise,
    creates a participant_two and calls get_destinations function.
    '''
    if request.method == 'POST':
        meeting = models.Meeting.objects.get(trip_id = trip_id)
        if meeting.participant_two:
            #If second participant already added, redirects to results
            return redirect('meethalfway:results', trip_id)
        address = AddAddress(request.POST)
        participant = AddParticipant(request.POST)
    
        if address.is_valid() and participant.is_valid():
            address_obj = address.save()
            #USPS api used to validate the entered address
            verify, suggestion, verified_address_dict = address_obj.verify_address()
            if verify:
                verified_address = models.Address(street = verified_address_dict['address'], city = verified_address_dict['city'], \
                state = verified_address_dict['state'], zip_code = verified_address_dict['zip5'])
                verified_address.save()
                address_obj.delete()

                part_obj = participant.save()
                part_obj.starting_location = verified_address
                part_obj.save()

                meeting.participant_two = part_obj
                meeting.save()
                meeting.get_destinations()

            else:
                return redirect('meethalfway:address_error2', trip_id, suggestion)
            return redirect('meethalfway:results', trip_id)
    address = AddAddress()
    participant = AddParticipant()

    c = {
        'forms': [address, participant],
        'uniq': trip_id
    }
    return render(request, "halfwayapp/person2.html", c)


def results(request, trip_id):
    '''
    When called, finds the Meeting object associated with the trip id. Shows the
    destination results if any were found and displays error message otherwise.
    '''
    meeting = models.Meeting.objects.get(trip_id = trip_id)
    d = meeting.destinations.order_by('score')
    if not d.exists():
        return redirect('meethalfway:no_results')
    destinations = d.reverse()
    best_dest = destinations[:1].get().latlng
    lat = best_dest.split(",")[0]
    lng = best_dest.split(",")[1]

    c = {
        'destinations': destinations,
        'trip_id': trip_id,
        'lat': lat,
        'lng': lng
    }
    return render(request, "halfwayapp/results.html", c)


def about(request):
    '''
    Displays 'about' page with information about site.
    '''
    return render(request, "halfwayapp/about.html")

def no_results(request):
    '''
    Displays an error page if no potential destinations were found.
    '''
    return render(request, "halfwayapp/no_results.html")

def contact(request):
    '''
    Displays 'contact' page.
    '''
    return render(request, "halfwayapp/contact.html")


def address_error1(request, suggestion):
    '''
    Displays error message if first participant's address is invalid.
    '''
    c = {
        'suggestion': suggestion
    }
    return render(request, "halfwayapp/address_error1.html", c)


def address_error2(request, trip_id, suggestion):
    '''
    Displays error message if second participant's address is invalid.
    '''
    c = {
        'trip_id': trip_id,
        'suggestion': suggestion
    }
    return render(request, "halfwayapp/address_error2.html", c)

meethalfway/templates/halfwayapp/about.html
{# About Page #}
{% extends "halfwayapp/base.html" %} {% block content %} {% load staticfiles %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h1>
			About </h1>
		</div>
		<p class="lead">
			 Find a convenient place to meet, safely and securely. Meet Halfway makes it easy to find a place to meet a friend or stranger that's convenient for both of you.
		</p>
	</div>
	<div class="row">
		<div class='col-sm-3 col-sm-offset-1'>
			<h2 class='text-center'>
			<span class="glyphicon glyphicon-home">
			</h2>
			<br>
			<p>
				 Enter your starting point, transit mode, and type of place you want to meet
			</p>
		</div>
		<div class='col-sm-3'>
			<h2 class='text-center'>
			<span class="glyphicon glyphicon-send">
			</span>
			</h2>
			<br>
			<p>
				 Send a link to your friend to separately enter their address and transit mode
			</p>
		</div>
		<div class='col-sm-3'>
			<h2 class='text-center'>
			<span class="glyphicon glyphicon-thumbs-up">
			</span>
			</h2>
			<br>
			<p>
				 Discover destinations with roughly equal travel times for both of you
			</p>
		</div>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/address_error1.html
{# Displayed when address cannot be found for participant one. #}
{% extends "halfwayapp/base.html" %} {% block content %} {% load staticfiles %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h1>Sorry, we couldn't match this address.</h1>
			<h2>{{suggestion}}</h2>
		</div>
		<h3>Please try again</h3>
		<a class="btn btn-primary" href="/home" role="button">Return to the homepage</a>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/address_error2.html
{# Displayed when address cannot be found for participant two. #}
{% extends "halfwayapp/base.html" %} {% block content %} {% load staticfiles %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h1>Sorry, we couldn't match this address</h1>
			<h2>{{suggestion}}</h2>
		</div>
		<h3>Please try again</h3>
		<a class="btn btn-primary" href="/participant_two/{{trip_id}}" role="button">Go back</a>
    </div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/base.html
<!-- Most of this is a lightly modified version of the index.html file from this
Bootstrap template: http://startbootstrap.com/template-overviews/logo-nav/ -->
<!DOCTYPE html>
{% load staticfiles %} <html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Meet Halfway</title>

<!-- Bootstrap Core CSS -->
<link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
<!-- Bootstrap Custom CSS -->
<link href="{% static "bootstrap/css/logo-nav.css" %}" rel="stylesheet">
<!-- Meet Halfway Custom CSS -->
<link href="{% static "css/stylesheet.css" %}" rel="stylesheet">
<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway:600' rel='stylesheet' type='text/css'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'meethalfway:home' %}">
		<img src="{% static "bootstrap/images/font-logo.png" %}" alt="">
		</a>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li>
			<a href="{% url 'meethalfway:about' %}">About</a>
			</li>
			<li>
			<a href="{% url 'meethalfway:contact' %}">Contact</a>
			</li>
		</ul>
	</div>
	<!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>
{% block content %} {% endblock %}

<!-- Footer -->
<footer>
<div class="container">
	<div class="col-lg-12">
		<p>
			Meet Halfway © 2016. A project for CS122, University of Chicago.
		</p>
	</div>
	<!-- /.row -->
</div>
</footer>

<!-- Bootstrap jQuery -->
<script src="{% static "bootstrap/js/jquery.js" %}"></script>
<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
<!-- Custom or borrowed jQuery for CSS animation and fairness score tooltip on results page-->
<script src="{% static "js/jquery.js" %}"></script>

</body>
</html>

meethalfway/templates/halfwayapp/contact.html
{# Contact Page #}
{% extends "halfwayapp/base.html" %} {% block content %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h1>Contact</h1>
		</div>
		<p class="lead">
			We'd love to hear from you.
		</p>
		<p>
			Contact us: ladyson [at] uchicago [dot] edu
		</p>
		<p>
			This project is licensed under the Apache License, Version 2.0. Find our code on <a href="https://github.com/ladyson/pllc">github</a>.
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/home.html
{# Home Page #}
{% extends "halfwayapp/base.html" %} {% load bootstrap %} {% block content %}

<header class="business-header">
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<br>
			<br>
			<h1 class="tagline text-center">Let's meet halfway</h1>
			<h4 class='tagline-small text-center'>Discover convenient places to meet up, safely and securely.</h4>
		</div>
	</div>
</div>
</header>
<div class='container'>
	<div class='page-header'>
		<h2>Get started.</h2>
	</div>
	<div class="row">
		<div class='col-sm-3 panel panel-default'>
			<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
			<h5 class='text-center'>1. Enter your starting point</h5>
		</div>
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
			<h5 class='text-center'>2. Share link with your friend</h5>
		</div>
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
			<h5 class='text-center'>3. Friend enters their address</h5>
		</div>
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon glyphicon-map-marker"></span></h4>
			<h5 class='text-center'>4. View your results</h5>
		</div>
	</div>
	<hr>
	<div class='row'>
		<div class="col-sm-7">
			<form method="post" class="form-horizontal">
				 {% csrf_token %}
				<table class='table'>
				 {% for form in forms %} {{ form|bootstrap_horizontal }} {% endfor %}
				</table>
				<div class="form-group">
					<div class="col-sm-10 col-sm-offset-2">
						<input type="submit" name="participant_one_submit" value="Submit" class="btn btn-default"/></input>
					</div>
				</div>
			</form>
		</div>
		<div class="col-sm-4 col-sm-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Already have a meeting started?</h4>
				</div>
				<div class='panel-body'>
					<p>
						Enter your meeting id to add your address or view results.
					</p>
					<form method="post">
						 {% csrf_token %}
						<table class="table">
						 {{ trip_id_form|bootstrap }}
						</table>
						<input type="submit" name="enter_trip_id" value="Submit" class="btn btn-default"/>
					</form>
					 {% if not_found %} <br>
					<div class="alert alert-danger" role="alert">
						<strong>Whoops!</strong> That meeting ID does not exist.
					</div>
					 {% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/no_results.html
{# Displayed when none is returned from get_destinations call in meetings class #}
{% extends "halfwayapp/base.html" %} {% block content %} {% load staticfiles %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h1>Whoops!</h1>
		</div>
		<h3>Sorry, we couldn't find any meeting points that matched your specifications. Please try again.</h3>
		<a class="btn btn-primary" href="/home.html" role="button">Return to the homepage</a>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/person2.html
{# Form 2 for Participant Two #}
{% extends "halfwayapp/base.html" %} {% load bootstrap %} {% block content %}

{# CSS Loading Animation #}
<div class="loader-outer hidden">
	<div class="loader-wrapper">
		<p>
			Hold on tight! We're finding the best meeting places for you.
		</p>
	</div>
	<div class="loader-inner ball-zig-zag">
		<div>
		</div>
		<div>
		</div>
	</div>
</div>

<div class="container" id="part2-container">
	<div class="row">
		<div class='col-sm-12'>
			<div class='page-header'>
				<h2>Add your starting address.</h2>
			</div>
		</div>
		<div class="row">
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
				<h5 class='text-center'>1. Enter your starting point</h5>
			</div>
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
				<h5 class='text-center'>2. Share link with your friend</h5>
			</div>
			<div class='col-sm-3 panel panel-default'>
				<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
				<h5 class='text-center'>3. Friend enters their address</h5>
			</div>
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon glyphicon-map-marker"></span></h4>
				<h5 class='text-center'>4. View your results</h5>
			</div>
		</div>
		<hr>
		<div class="col-md-offset-2 col-md-10">
			<p class="lead">
				Enter your starting point below.
			</p>
			<div class="row">
				<div class='col-sm-9' id="part2-form">
					<form method="post" class="form-horizontal">
						 {% csrf_token %}
						<table class="table">
						 {% for form in forms %} {{ form|bootstrap_horizontal }} {% endfor %}
						</table>
						<div class="form-group">
							<div class="col-sm-10 col-sm-offset-2">
								<input type="submit" name="PersonB_submit" value="Submit Address" class="btn btn-default"/>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/response.html
{# Landing page after first form. Displays meeting name. #}
{% extends "halfwayapp/base.html" %} {% block content %} {% load staticfiles %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h2>Alright! You're almost halfway there.</h2>
		</div>
		<div class="row">
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
				<h5 class='text-center'>1. Enter your starting point</h5>
			</div>
			<div class='col-sm-3 panel panel-default'>
				<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
				<h5 class='text-center'>2. Share link with your friend</h5>
			</div>
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon-unchecked"></span></h4>
				<h5 class='text-center'>3. Friend enters their address</h5>
			</div>
			<div class='col-sm-3'>
				<h4 class='text-center'><span class="glyphicon glyphicon glyphicon-map-marker"></span></h4>
				<h5 class='text-center'>4. View your results</h5>
			</div>
		</div>
		<hr>
		<div class="col-md-offset-2 col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Send your friend this code (make sure you save it for yourself too!):
					</hr>
				</div>
				<div class="panel-body">
                    <!-- clipboard js and instructions from https://clipboardjs.com/ -->
					<script src="{% static "clipboard/clipboard.min.js" %}"></script>
					<script>
                    var clipboard = new Clipboard('.btn');
                    </script>
					<!-- Target -->
					<div class="row">
						<div class="col-lg-12">
							<div class="input-group">
								<input class="form-control" id="copyid" value="{{uniq}}">
								<!-- Trigger -->
								<span class="input-group-btn">
								<button class="btn btn-default" data-clipboard-target="#copyid">
								<span class='glyphicon glyphicon-copy'></span>
								<!-- img src="../static/clipboard/assets/noun_168961_cc.svg" alt="Copy to clipboard" -->
								 Copy to clipboard </button>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<span>
			<div class=container4>
				<p>
					or...
				</p>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Email them this message:
					</hr>
				</div>
				<div class="panel-body">
					<!-- Target -->
					<div class="row">
						<div class="col-lg-12">
							<textarea id="fulltext" rows="3" cols="60" style="width:100%">Meet me halfway! Go to www.meethalfway.io/participant_two/{{uniq}} to fill out your address. You can also look up our meeting by pasting {{uniq}} into the meeting finder at www.meethalfway.io </textarea>
						</div>
					</div>
					<!-- Trigger -->
					<div class="row">
						<div class="col-sm-4">
							<button class="btn btn-default" data-clipboard-target="#fulltext">
							<span class='glyphicon glyphicon-copy'></span>
							Copy to clipboard </button>
						</div>
					</div>
				</div>
			</div>
			<div>
				<h3>What now?</h3>
				<a class="btn btn-primary" href="/participant_two/{{uniq}}" role="button">Go to your meeting</a> or <a class="btn-link" href="{% url 'meethalfway:home' %}" role="button">return to the homepage.</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

meethalfway/templates/halfwayapp/results.html
{# Displays Final Results #}
{% extends "halfwayapp/base.html" %} {% block content %}

<div class="container">
	<div class="row">
		<div class='page-header'>
			<h2>Results</h2>
		</div>
	</div>
	<div class="row">
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
			<h5 class='text-center'>1. Enter your starting point</h5>
		</div>
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
			<h5 class='text-center'>2. Share link with your friend</h5>
		</div>
		<div class='col-sm-3'>
			<h4 class='text-center'><span class="glyphicon glyphicon-check"></span></h4>
			<h5 class='text-center'>3. Friend enters their address</h5>
		</div>
		<div class='col-sm-3 panel panel-default'>
			<h4 class='text-center'><span class="glyphicon glyphicon glyphicon-map-marker"></span></h4>
			<h5 class='text-center'>4. View your results</h5>
		</div>
	</div>
	<hr>
	<div class='row'>
		<div class='col-sm-5'>
			<div class="list-group">
				 {% for destination in destinations %}
				<li class="list-group-item">
				<h4><span class="glyphicon glyphicon-map-marker"></span> {{ destination.name }}</h4>
				<ul class="list-unstyled">
					<li>
					<h5>{{ destination.address }}</h5>
					</li>
					<li>Fairness score: {{ destination.score }} <span data-toggle="tooltip" data-placement="right" title="The fairness score is a measure of how equal the travel times are. 100 is perfectly equal." style="padding-left:5px;"><span class="glyphicon glyphicon-question-sign"></span></span></li>
					<li>Approximate travel time: {{ destination.avg_time }} mins</li>
				</ul>
				<button id="{{ destination.latlng }}" class="btn btn-default btn-xs" onclick="newLocation(this.id);">View on map</button>
				</br>
				</li>
				 {% endfor %}
			</div>
		</div>
		<div class='col-sm-7'>
			<div id="map">
			</div>
		</div>
	</div>
	<!--     The code for embedding a Google Map and panning on click was adapted from an example at:
    http://stackoverflow.com/questions/28499141/how-to-change-google-map-center-by-clicking-a-button -->
	<script>
        var map;
        function initMap() {
            var best_latlng = {lat: {{ lat }}, lng: {{ lng }}};
            var mapDiv = document.getElementById('map');
            map = new google.maps.Map(mapDiv, {
              center: best_latlng,
              zoom: 19
            });
            var marker = new google.maps.Marker({
              position: best_latlng,
              map: map
            });
        }
        function newLocation(latlng) {
            var destlatlng = new google.maps.LatLng(latlng.split(",")[0], latlng.split(",")[1]);
            map.panTo(destlatlng);
            var marker = new google.maps.Marker({
                position: destlatlng,
                map: map,
                title: "dest"
            });
        }
      </script>
	<script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script>
</div>

{% endblock %}